nelmio_api_doc:
    documentation:
        info:
            title: BileMo
            description: Cell catalog
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns: [^/api/products, ^/api.users]
